### PR TITLE
fixes for 3.18

### PR DESCRIPTION
**Pull request by gutenye**

### CODE REVIEW

**Comment by l300lvl** [comment]
This is not a fix but more of a patch, I will update it when time allows. 3.18 has not been out that long and upgrading F22>F23 broke my system, so I have to reinstall fed from scratch. Thank you for opening this, though. If it's working for you that is great, but have you also checked terminal for session errors by running gnome-shell --replace and looking for any problems this extension may have other than just the version number needing changed?

**Comment by gutenye** [comment]
Yeah, it's quick rough patch :(
One more thing, the 'Settings Center' menu is moved to the bottom, instead at the middle as previous version.

**Comment by careca1970** [comment]
Thank you, gutenye!
The few changes in "extension.js" and adding 3.18 to "metadata.json" is enough to bring this nice extension back to life.
Please, update the master!

**Comment by Astinus-Eberhard** [comment]
Hey. Any signs that it will be merged soon?

**Pull request closed without merging**
